- name: "RHV: HE Backup"
  hosts: virt-console
  become: yes
  tags: he-backup

  vars:
    retention_days: 1w

  tasks:
    - ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../../roles/pinguozzo.ovirt-he-backup"
